apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.team }}-{{ .Values.project }}-{{ .Values.env }}
  labels:
    team: {{ .Values.team | quote }}
    project: {{ .Values.project | quote }}
    env: {{ .Values.env | quote }}
    managed-by: "namespace-factory"
  annotations:
    argocd.argoproj.io/sync-wave: "-5"