apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.team }}-{{ .Values.project }}-admin-binding
  namespace: {{ .Values.team }}-{{ .Values.project }}-{{ .Values.env }}
  labels:
    team: {{ .Values.team | quote }}
    project: {{ .Values.project | quote }}
    env: {{ .Values.env | quote }}
    managed-by: "namespace-factory"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: {{ .Values.rbac.groups.admin | quote }}
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: {{ .Values.project }}-pipeline-deployer
    namespace: {{ .Values.team }}-{{ .Values.project }}-{{ .Values.env }}