{{- if .Values.rbac.groups.viewer }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.team }}-{{ .Values.project }}-view-binding
  namespace: {{ .Values.team }}-{{ .Values.project }}-{{ .Values.env }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: {{ .Values.rbac.groups.viewer | quote }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}