apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.project }}-quota
  namespace: {{ .Values.team }}-{{ .Values.project }}-{{ .Values.env }}
  labels:
    team: {{ .Values.team | quote }}
    project: {{ .Values.project | quote }}
    env: {{ .Values.env | quote }}
    managed-by: "namespace-factory"
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  hard:
    requests.cpu: {{ .Values.quota.cpu.requests | quote }}
    limits.cpu: {{ .Values.quota.cpu.limits | quote }}
    requests.memory: {{ .Values.quota.memory.requests | quote }}
    limits.memory: {{ .Values.quota.memory.limits | quote }}