apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.project }}-pipeline-deployer
  namespace: {{ .Values.team }}-{{ .Values.project }}-{{ .Values.env }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"